### ISSUE TITLE
Error: Failed to precompile LarSurf, LoadError: syntax: "using" expression not at top level

### ISSUE THREAD

**Issue by vcaravani** [mjirik/LarSurf.jl#1]
Hi mjirik, I found that in the file larsurf_experiments.jl there is a "using" within a function, moving it out I could run the example of the tetris that first gave me error

**Comment by mjirik** [comment]
I forgot to include the file. I will fix it as soon as possible. I will let
you know when it will be ready.

Best
MJ

Dne so 16. 11. 2019 16:47 uživatel vcaravani <notifications@github.com>
napsal:

**Comment by mjirik** [comment]
It should be repaired now.

There are tests passing for julia 1.1 and 1.2

I had to change the bame of ExSu package to ExSup because of naming
conventions on Julia package registration procedure.

It is in described inReadme file.

Let me know...

Best regards,
Mira



Dne so 16. 11. 2019 17:31 uživatel Miroslav Jiřík <miroslav.jirik@gmail.com>
napsal:

**Comment by vcaravani** [comment]
Now everything seems to work :)

**Comment by mjirik** [comment]
Great! Thank you :-)

MJ

po 18. 11. 2019 v 11:20 odesílatel vcaravani <notifications@github.com>
napsal:
